# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ReactImageMap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ReactImageMap
  pod 'AMPopTip', :git => 'https://github.com/kaich/AMPopTip.git'
  pod 'CKImageMap', :git => 'https://github.com/kaich/CKImageMap.git'


  target 'ReactImageMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


target 'CKReactImageMap' do
    use_frameworks!
    pod 'AMPopTip', :git => 'https://github.com/kaich/AMPopTip.git'
    pod 'CKImageMap', :git => 'https://github.com/kaich/CKImageMap.git'
end
